name: My Awesome Home
views:
  - name: Home
    cards:
      - type: markdown
        content: >
          ## Lovelace

          Starting with Home Assistant 0.72, we're experimenting with a new way of defining your interface. We're calling it the **Lovelace UI**.
      - type: picture-glance
        image: https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=240&w=495
        title: Living
        entities:
          - switch.decorative_lights
          - light.ceiling_lights
          - lock.front_door
          - binary_sensor.movement_backyard
          - binary_sensor.basement_floor_wet
      - type: entity-filter
        filter:
          - domain: device_tracker
            state: 'home'
        card: glance
        card_config:
          title: People at home
      - type: entity-picture
        image: https://images.pexels.com/photos/775219/pexels-photo-775219.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=295&w=490
        entity: light.bed_light
      - type: weather-forecast
        entity: weather.demo_weather_north
      - type: entity-filter
        filter:
          - domain: light
            state: 'on'
          - domain: switch
            state: 'on'
        card_config:
          title: Eating power
      - type: entities
        title: Entities card sample
        entities:
          - alarm_control_panel.alarm
          - device_tracker.demo_paulus
          - switch.decorative_lights
          - group.all_lights
          - group.all_locks
      - type: glance
        title: Glance card sample
        entities:
          - binary_sensor.movement_backyard
          - light.bed_light
          - binary_sensor.basement_floor_wet
          - sensor.outside_temperature
          - light.ceiling_lights
          - switch.ac
          - lock.kitchen_door
      - type: entity-filter
        filter:
          - entity_id: '*kitchen*'
        card_config:
          title: Kitchen
      - type: entity-filter
        filter:
          - domain: light
        card: picture-glance
        card_config:
          title: Lights
          image: https://images.pexels.com/photos/356048/pexels-photo-356048.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=295&w=490
      - type: media-control
        entity: media_player.lounge_room
      - type: plant-status
        entity: plant.bonsai
      - type: history-graph
        entity: history_graph.recent_switches
  - tab_icon: mdi:video-image
    name: Multimedia
    cards:
      - type: media-control
        entity: media_player.bedroom
      - type: media-control
        entity: media_player.walkman
      - type: camera-preview
        entity: camera.demo_camera
      - type: media-control
        entity: media_player.living_room
      - type: media-control
        entity: media_player.lounge_room
  - tab_icon: mdi:settings
    name: Debugging
    cards:
      - type: entity-filter
        filter: [{}]
        card_config:
          title: All entities